# Generated by Django 6.0.6 on 2026-06-28 10:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Repository',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Fichier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('chemin', models.CharField(max_length=500)),
                ('type_fichier', models.CharField(choices=[('source', 'Source'), ('config', 'Configuration'), ('doc', 'Documentation'), ('test', 'Test'), ('autre', 'Autre')], default='source', max_length=50)),
                ('langage', models.CharField(blank=True, default='', max_length=100)),
                ('taille', models.PositiveIntegerField(default=0)),
                ('description', models.TextField(blank=True, default='')),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('est_critique', models.BooleanField(default=False)),
                ('repository', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fichiers', to='repositories.repository')),
            ],
            options={
                'ordering': ['-date_ajout'],
            },
        ),
    ]
